name: 'Release new version'
on:
  push:
    tags:
      - '*.*.*'
      
jobs:
  release-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create backend application image
        run: docker build -t eternalwanderer/docker-back:latest -t eternalwanderer/docker-back:${{ env.RELEASE_VERSION }} -f ./Dockerfile .

      - name: Login in to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish new backend application image
        run: |
          docker push eternalwanderer/docker-back:latest
          docker push eternalwanderer/docker-back:${{ env.RELEASE_VERSION }}
